[workspace]
members = [".", "third_party/ls-types"]
default-members = ["."]
resolver = "2"

[package]
name = "fluent-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
fluent-syntax = { git = "https://github.com/juliancoffeelab/fluent-rs", branch = "span-followup", package = "fluent-syntax", features = [
    "spans",
] }
icu = { version = "2.2", features = ["compiled_data"] }
regex = "1.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.23"
tokio = { version = "1.48", features = [
    "fs",
    "io-std",
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
toml = "0.9"
tower-lsp = { package = "tower-lsp-server", version = "0.23.0", features = [
    "proposed",
] }

[dev-dependencies]
fluent-bundle = { git = "https://github.com/juliancoffeelab/fluent-rs", branch = "span-followup", package = "fluent-bundle" }
unic-langid = "0.9.6"

[patch.crates-io]
ls-types = { path = "third_party/ls-types" }
